name: OpenMCx build
on: [push]
jobs:
  Build-OpenMCx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.workspace }}
          ls ${{ github.workspace }}
      - uses: ./.github/actions/build-action
